<?php

class m130709_225606_build_tables extends CDbMigration
{
	public function safeUp()
	{
		$this->createTable('FORMS', array(
            'FORM_ID' => 'pk',
			'TABLE_NAME' => 'VARCHAR(128)',
			'FORM_NAME' => 'VARCHAR(128)',
			'BEGIN_DATE' => 'TIMESTAMP NOT NULL DEFAULT "0000-00-00 00:00:00"',
			'END_DATE' => 'TIMESTAMP NOT NULL DEFAULT "0000-00-00 00:00:00"',
			'TYPE_ID' => 'INT(10)',
			
			'CREATED_BY' => 'VARCHAR(255)',
			'LAST_MODIFIED_BY' => 'VARCHAR(255)',
			'CREATED_DATE' => 'TIMESTAMP NOT NULL DEFAULT "0000-00-00 00:00:00"',
			'LAST_MODIFIED_DATE' => 'TIMESTAMP NOT NULL DEFAULT "0000-00-00 00:00:00" ON UPDATE CURRENT_TIMESTAMP',
        ));

		$this->createTable('FORM_FIELDS', array(
            'FIELD_ID' => 'pk',
			'FORM_ID' => 'INT(10)',
			'VARNAME' => 'VARCHAR(50) NOT NULL DEFAULT ""',
			'TITLE' => 'VARCHAR(255) NOT NULL DEFAULT ""',
			'FIELD_TYPE' => 'VARCHAR(50) NOT NULL DEFAULT ""',
			'FIELD_SIZE' => 'INT(3) NOT NULL DEFAULT 0',
			'FIELD_SIZE_MIN' => 'INT(3) NOT NULL DEFAULT 0',
			'REQUIRED' => 'INT(1) NOT NULL DEFAULT 0',
			'MATCH' => 'VARCHAR(255) NOT NULL DEFAULT ""',
			'SELECT'=>'INT(1) NOT NULL DEFAULT 0',
			'RANGE' => 'VARCHAR(255) NOT NULL DEFAULT ""',
			'ERROR_MESSAGE' => 'VARCHAR(255) NOT NULL DEFAULT ""',
			'OTHER_VALIDATOR' => 'TEXT',
			'DEFAULT' => 'VARCHAR(255) NOT NULL DEFAULT ""',
			'WIDGET' => 'VARCHAR(255) NOT NULL DEFAULT ""',
			'WIDGETPARAMS' => 'TEXT',
			'POSITION' => 'INT(3) NOT NULL DEFAULT 0',
			'VISIBLE' => 'INT(1) NOT NULL DEFAULT 0',
			
			'CREATED_BY' => 'VARCHAR(255)',
			'LAST_MODIFIED_BY' => 'VARCHAR(255)',
			'CREATED_DATE' => 'TIMESTAMP NOT NULL DEFAULT "0000-00-00 00:00:00"',
			'LAST_MODIFIED_DATE' => 'TIMESTAMP NOT NULL DEFAULT "0000-00-00 00:00:00" ON UPDATE CURRENT_TIMESTAMP',
        ));

		$this->createTable('TYPES', array(
            'TYPE_ID' => 'pk',
			'TYPE_LABEL' => 'VARCHAR(255)',
			
			'CREATED_BY' => 'VARCHAR(255)',
			'LAST_MODIFIED_BY' => 'VARCHAR(255)',
			'CREATED_DATE' => 'TIMESTAMP NOT NULL DEFAULT "0000-00-00 00:00:00"',
			'LAST_MODIFIED_DATE' => 'TIMESTAMP NOT NULL DEFAULT "0000-00-00 00:00:00" ON UPDATE CURRENT_TIMESTAMP',
        ));
	}

	public function safeDown()
	{
		$this->dropTable('FORMS');
		$this->dropTable('FORM_FIELDS');
		$this->dropTable('TYPES');
	}

}